language: python

python:
  - "2.7"

install:
    - pip install -r requirements/common.txt

notifications:
  email:
    on_success: change
    on_failure: always

services: mongodb

script:
    - python manage.py test
