language: python

python:
  - "2.7"

env:
    - FLASK_APP=commands.py

install:
    - pip install -r requirements/common.txt

notifications:
  email:
    on_success: change
    on_failure: always

services: mongodb

script:
    - cp config.yml.example config.yml
    - flask test
