COMMON: &common
  DEBUG: False
  TESTING: False
  SECRET_KEY: 't0p s3cr3t'
  SSL_DISABLE: False
  OAUTH_CLIENT_ID: 'CLIENT_ID'
  OAUTH_CLIENT_SECRET: 'CLIENT_SECRET'
  DEFAULT_LANG: 'de'
  URL_TOKENINFO: 'https://example.com/tokeninfo'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  MONGOALCHEMY_DATABASE: 'msdevelopment'

PRODUCTION: &production
  <<: *common
  MONGOALCHEMY_DATABASE: 'msregistry'

TESTING: &testing
  TESTING: True
  MONGOALCHEMY_DATABASE: 'msdevelopment'

DEFAULT: &default
  <<: *development
