COMMON: &common
  DEBUG: False
  TESTING: False
  SECRET_KEY: 't0p s3cr3t'
  SSL_DISABLE: False
  MAIL_SERVER: 'smtp.googlemail.com'
  MAIL_PORT: 587
  MAIL_USE_TLS: True
  MAIL_USERNAME: 'MAIL_USERNAME'
  MAIL_PASSWORD: 'MAIL_PASSWORD'
  MAIL_SUBJECT_PREFIX: 'MAIL_SUBJECT_PREFIX'
  MAIL_SENDER: '<info@example.com>'
  OAUTH_CLIENT_ID: 'CLIENT_ID'
  OAUTH_CLIENT_SECRET: 'CLIENT_SECRET'
  BABEL_DEFAULT_LOCALE: 'de'
  LANGUAGES: {'de': 'Deutsch', 'fr': 'Français', 'it': 'Italiano'}
  URL_TOKENINFO: 'https://example.com/tokeninfo'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  MONGODB_DB: 'msdevelopment'

PRODUCTION: &production
  <<: *common
  MONGODB_DB: 'msregistry'
  MONGODB_USERNAME: 'webapp'
  MONGODB_PASSWORD: 'pwd123'

TESTING: &testing
  TESTING: True
  MONGODB_DB: 'msdevelopment'

DEFAULT: &default
  <<: *development
