COMMON: &common
  DEBUG: False
  TESTING: False
  SECRET_KEY: 't0p s3cr3t'
  SSL_DISABLE: False
  OAUTH_CERTIFICATE: |
    -----BEGIN PUBLIC KEY-----
    -----END PUBLIC KEY-----

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  MONGOALCHEMY_DATABASE: 'msdevelopment'

PRODUCTION: &production
  <<: *common
  MONGOALCHEMY_DATABASE: 'msregistry'

TESTING: &testing
  TESTING: True
  MONGOALCHEMY_DATABASE: 'msdevelopment'

DEFAULT: &default
  <<: *development
