COMMON: &common
  DEBUG: False
  TESTING: False
  SECRET_KEY: 't0p s3cr3t'
  SSL_DISABLE: False
  SQLALCHEMY_COMMIT_ON_TEARDOWN: True
  SQLALCHEMY_RECORD_QUERIES: True
  SQLALCHEMY_TRACK_MODIFICATIONS: True
  MAIL_SERVER: 'smtp.googlemail.com'
  MAIL_PORT: 587
  MAIL_USE_TLS: True
  MAIL_USERNAME: 'MAIL_USERNAME'
  MAIL_PASSWORD: 'MAIL_PASSWORD'
  MAIL_SUBJECT_PREFIX: 'MAIL_SUBJECT_PREFIX'
  MAIL_SENDER: '<info@example.com>'
  SLOW_DB_QUERY_TIME: 0.5
  OAUTH_CLIENT_ID: 'CLIENT_ID'
  OAUTH_CLIENT_SECRET: 'CLIENT_SECRET'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'sqlite:////sqlite/data-dev.sqlite'

PRODUCTION: &production
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'sqlite:////sqlite/data-dev.sqlite'

TESTING: &testing
  TESTING: True
  SQLALCHEMY_DATABASE_URI: 'sqlite:////sqlite/data-dev.sqlite'
  WTF_CSRF_ENABLED: False

DEFAULT: &default
  <<: *development
